name: Build and release
on:
  push:
    branches:
      - main

jobs:
  build:
    if: "startsWith(github.event.head_commit.message, 'Release: ')"
    strategy:
      matrix:
        include:
          - runner: macos-26-intel
            arch: intel
          - runner: macos-26
            arch: arm64
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v6
      - name: Setup Java JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Run all tests
        run: ./gradlew test
      - name: Install the Apple certificate
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          KEYCHAIN_PASSWORD=$(openssl rand -hex 12)

          # import certificate from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH login.keychain-db
      - name: Create app bundle with Gradle (${{ matrix.arch }})
        run: ./gradlew creatAppBundle
      - run: mv ./build/app/KubeLog.pkg ./build/app/KubeLog-${{ matrix.arch }}.pkg
      - name: Upload artifact (${{ matrix.arch }})
        uses: actions/upload-artifact@v7
        with:
          name: kubelog-installer-${{ matrix.arch }}
          path: ./build/app/KubeLog-${{ matrix.arch }}.pkg
          retention-days: 1

  release:
    needs: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Java JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          pattern: kubelog-installer-*
          path: ./artifacts
          merge-multiple: true
      - name: Get app version
        id: app_version
        run: echo "APP_VERSION=$(./gradlew version --no-daemon --console=plain -q | tail -n 1)" >> $GITHUB_OUTPUT
      - name: Get short SHA
        id: short_sha
        run: echo "SHA8=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT
      - name: Create GH Release
        env:
          APP_VERSION: ${{ steps.app_version.outputs.APP_VERSION }}-${{ steps.short_sha.outputs.SHA8 }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v$APP_VERSION" \
            -t "Release v$APP_VERSION" \
            --generate-notes \
            './artifacts/KubeLog-intel.pkg#KubeLog-installer-mac-intel.pkg' \
            './artifacts/KubeLog-arm64.pkg#KubeLog-installer-mac-arm64.pkg'
